# Generated by Django 5.2.7 on 2026-02-14 06:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'bus_stop',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=150)),
                ('headsign', models.CharField(max_length=150)),
                ('route_long_name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'matatu_route',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, null=True)),
                ('category', models.CharField(default=None, max_length=100, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, null=True)),
                ('county', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/%Y/%m/%d/')),
                ('pets_allowed', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('num_bedrooms', models.IntegerField(default=None, null=True)),
                ('num_bathrooms', models.IntegerField(default=None, null=True)),
                ('square_meters', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('amenities', models.JSONField(default=None, null=True)),
                ('owner_contact', models.CharField(default=None, max_length=100, null=True)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rentals.district')),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.building')),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.profile')),
            ],
            options={
                'db_table': 'profile_building',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.ManyToManyField(related_name='profiles', through='rentals.ProfileBuilding', to='rentals.building'),
        ),
    ]
