# Generated by Django 5.2.7 on 2026-02-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuilding',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.building'),
        ),
        migrations.AlterField(
            model_name='profilebuilding',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.profile'),
        ),
        migrations.AddConstraint(
            model_name='profilebuilding',
            constraint=models.UniqueConstraint(fields=('building', 'profile'), name='unique_building_profile'),
        ),
    ]
