# Generated by Django 5.2.7 on 2025-11-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='building',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='title',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
