# Generated by Django 5.2.7 on 2025-11-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_building_available_from_building_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
