# Generated by Django 5.2.7 on 2025-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_building_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='square_footage',
        ),
        migrations.AddField(
            model_name='building',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
