# Generated by Django 5.2.7 on 2026-02-01 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_district_alter_building_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'bus_stop',
            },
        ),
    ]
