# Generated by Django 5.2.7 on 2026-02-01 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_busstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=150)),
                ('headsign', models.CharField(max_length=150)),
                ('route_long_name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'matatu_route',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='district',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
