# Generated by Django 5.2.7 on 2026-02-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_route_shops_alter_busstop_name_alter_district_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
