# Generated by Django 5.2.7 on 2025-11-02 12:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(default=None, max_length=100, null=True)),
                ('district', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('num_bedrooms', models.IntegerField(default=None, null=True)),
                ('num_bathrooms', models.IntegerField(default=None, null=True)),
                ('square_footage', models.IntegerField(default=None, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(default=None, null=True)),
                ('amenities', models.JSONField(default=None, null=True)),
                ('owner_contact', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=15, null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.building')),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.profile')),
            ],
            options={
                'db_table': 'profile_building',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.ManyToManyField(related_name='profiles', through='rentals.ProfileBuilding', to='rentals.building'),
        ),
    ]
